import { useEffect, useMemo, useState } from 'react';
import { api, formatNumber, formatCompact } from '../api/queries';
import Sparkline from '../components/Sparkline';
import type { Demo, DemoUsage } from '../types';

// ============================================================
// Usage page — "who is using the demos" in aggregate, anonymously.
//
// Two data sources, layered:
//
//  1. usage.json (always present, generated by build_snapshot.py).
//     Synthesised 30-day series + geo + top pages per demo. Useful
//     as a directional view of what a real analytics pipeline would
//     surface if Plausible / Umami / Snowplow were wired into each
//     demo. Marked "Preview" in the UI.
//
//  2. github_traffic.json (optional, fetched by the daily workflow
//     when TRAFFIC_PAT is configured). Real GitHub Pages traffic for
//     each demo repo: views, uniques, top paths, top referrers.
//     Layered into the page when available.
//
// Everything here is aggregate and anonymous — no user IDs ever,
// uniques are cookie-deduplicated by GitHub. See the "what we can
// see / can't see" footer for the explicit privacy frame.
// ============================================================

// --- Real GitHub-traffic shape (matches fetch-traffic.sh output) ---
type ViewPoint = { timestamp: string; count: number; uniques: number };
type Views14d  = { count: number; uniques: number; views: ViewPoint[] };
type PopularPath = { path: string; title: string; count: number; uniques: number };
type Referrer = { referrer: string; count: number; uniques: number };
type DemoTraffic = {
  repo: string;
  views_14d: Views14d;
  popular_paths: PopularPath[];
  top_referrers: Referrer[];
};
type GhSnapshot = {
  fetched_at: string;
  owner: string;
  demos: DemoTraffic[];
};

const BASE = (import.meta as any).env?.BASE_URL || './';

// ============================================================
// Page
// ============================================================

export default function TrafficPage() {
  const [usage, setUsage] = useState<DemoUsage[] | null>(null);
  const [demos, setDemos] = useState<Demo[] | null>(null);
  const [gh, setGh] = useState<GhSnapshot | null>(null);
  const [ghError, setGhError] = useState<string | null>(null);

  useEffect(() => {
    api.getUsage().then(setUsage).catch(() => setUsage([]));
    api.getDemos().then(setDemos).catch(() => setDemos([]));
    fetch(`${BASE}data/github_traffic.json`)
      .then((r) => (r.ok ? r.json() : Promise.reject(`HTTP ${r.status}`)))
      .then(setGh)
      .catch((e) => setGhError(String(e)));
  }, []);

  // ============================================================
  // Aggregations over the synth usage data
  // ============================================================
  const agg = useMemo(() => {
    if (!usage) return null;

    const totalViews    = usage.reduce((s, u) => s + u.trailing_30d.reduce((a, p) => a + p.page_views, 0), 0);
    const totalSessions = usage.reduce((s, u) => s + u.trailing_30d.reduce((a, p) => a + p.sessions, 0), 0);
    const totalUniques  = usage.reduce((s, u) => s + u.trailing_30d.reduce((a, p) => a + p.uniques, 0), 0);
    const sessionLengths = usage.flatMap((u) => u.trailing_30d.map((p) => p.avg_session_s));
    const avgSession = sessionLengths.length ? sessionLengths.reduce((a, b) => a + b, 0) / sessionLengths.length : 0;

    // Country rollup
    const geoMap = new Map<string, number>();
    for (const u of usage) {
      for (const g of (u.geo || [])) {
        geoMap.set(g.country, (geoMap.get(g.country) || 0) + g.sessions);
      }
    }
    const topCountries = Array.from(geoMap.entries())
      .sort((a, b) => b[1] - a[1])
      .slice(0, 12)
      .map(([country, sessions]) => ({ country, sessions }));

    // Top paths across all demos
    const pathMap = new Map<string, number>();
    for (const u of usage) {
      for (const p of (u.top_pages || [])) {
        const key = p.path;
        pathMap.set(key, (pathMap.get(key) || 0) + p.views);
      }
    }
    const topPaths = Array.from(pathMap.entries())
      .sort((a, b) => b[1] - a[1])
      .slice(0, 12)
      .map(([path, views]) => ({ path, views }));

    // Per-day aggregate (sum across demos by date)
    const byDate = new Map<string, { views: number; uniques: number; sessions: number }>();
    for (const u of usage) {
      for (const p of u.trailing_30d) {
        const slot = byDate.get(p.date) || { views: 0, uniques: 0, sessions: 0 };
        slot.views    += p.page_views;
        slot.uniques  += p.uniques;
        slot.sessions += p.sessions;
        byDate.set(p.date, slot);
      }
    }
    const series = Array.from(byDate.entries())
      .sort((a, b) => a[0].localeCompare(b[0]))
      .map(([date, v]) => ({ date, ...v }));

    // Per-demo rollup
    const perDemo = usage.map((u) => {
      const v = u.trailing_30d.reduce((s, p) => s + p.page_views, 0);
      const un = u.trailing_30d.reduce((s, p) => s + p.uniques, 0);
      const ses = u.trailing_30d.reduce((s, p) => s + p.sessions, 0);
      const trend = u.trailing_30d.map((p) => p.uniques);
      return { key: u.key, views: v, uniques: un, sessions: ses, trend };
    }).sort((a, b) => b.views - a.views);

    return { totalViews, totalSessions, totalUniques, avgSession, topCountries, topPaths, series, perDemo };
  }, [usage]);

  // ============================================================
  // Aggregations over the real GitHub Pages traffic
  // ============================================================
  const ghAgg = useMemo(() => {
    if (!gh) return null;
    const totalViews    = gh.demos.reduce((s, d) => s + (d.views_14d?.count ?? 0), 0);
    const totalUniques  = gh.demos.reduce((s, d) => s + (d.views_14d?.uniques ?? 0), 0);
    const withTraffic   = gh.demos.filter((d) => (d.views_14d?.count ?? 0) > 0).length;
    const noTraffic     = gh.demos.length - withTraffic;

    // Top referrers aggregated across demos
    const refMap = new Map<string, { count: number; uniques: number }>();
    for (const d of gh.demos) {
      for (const r of (d.top_referrers || [])) {
        const cur = refMap.get(r.referrer) || { count: 0, uniques: 0 };
        cur.count   += r.count;
        cur.uniques += r.uniques;
        refMap.set(r.referrer, cur);
      }
    }
    const topReferrers = Array.from(refMap.entries())
      .sort((a, b) => b[1].count - a[1].count)
      .slice(0, 15)
      .map(([referrer, v]) => ({ referrer, ...v }));

    return { totalViews, totalUniques, withTraffic, noTraffic, topReferrers };
  }, [gh]);

  const labelFor = (key: string) =>
    demos?.find((d) => d.key === key)?.name ?? key;

  // ============================================================
  // Render
  // ============================================================
  return (
    <div className="mc-page mx-auto max-w-[1440px] px-4 sm:px-6 lg:px-8 py-8 lg:py-12">
      <header className="mb-8">
        <p className="font-mono text-[10px] uppercase tracking-[0.3em]" style={{ color: 'var(--accent)' }}>
          Usage · aggregate-anonymous
        </p>
        <h1 className="mt-2 text-3xl sm:text-4xl font-semibold tracking-tight" style={{ color: 'var(--ink)' }}>
          Who is using the demos — even when we can't identify them.
        </h1>
        <p className="mt-3 max-w-3xl leading-relaxed" style={{ color: 'var(--ink-muted)' }}>
          Aggregate, cookie-deduplicated visit signal — no user IDs, no sessions tied to identity.
          Two layered sources: a 30-day usage preview synthesised from the portfolio's connector
          mix, and (when live) the GitHub Pages traffic API's 14-day rolling window per repo.
        </p>
      </header>

      {/* Portfolio totals (synth) */}
      {agg && (
        <>
          <section className="mb-8 grid grid-cols-2 md:grid-cols-4 gap-3">
            <Kpi big={formatCompact(agg.totalViews)} label="Page views · 30d" sub={formatNumber(agg.totalViews)} />
            <Kpi big={formatCompact(agg.totalUniques)} label="Unique visitors · 30d" sub={`${formatNumber(agg.totalUniques)} cookie-deduped`} />
            <Kpi big={formatCompact(agg.totalSessions)} label="Sessions · 30d" sub={formatNumber(agg.totalSessions)} />
            <Kpi big={`${Math.round(agg.avgSession / 60)}m ${Math.round(agg.avgSession % 60)}s`} label="Avg session length" sub={`${Math.round(agg.avgSession)} seconds`} />
          </section>

          <PreviewBanner />

          {/* Daily activity */}
          <section className="mb-10">
            <SectionHeader title="Daily activity · 30 days" sub="Page views and unique visitors per day, summed across the portfolio." />
            <DailySeries series={agg.series} />
          </section>

          {/* Where they come from + top paths */}
          <section className="mb-10 grid lg:grid-cols-2 gap-6">
            <Card title="Where they come from" sub="Top countries by session count · synth preview">
              <BarList rows={agg.topCountries.map((c) => ({ label: c.country, value: c.sessions }))} valueLabel="sessions" />
            </Card>
            <Card title="Most-visited paths · across portfolio" sub="Aggregated from each demo's top-pages table">
              <BarList rows={agg.topPaths.map((p) => ({ label: p.path, value: p.views }))} valueLabel="views" mono />
            </Card>
          </section>

          {/* Top demos */}
          <section className="mb-10">
            <SectionHeader title="Top demos · 30-day uniques" sub="Sorted by total page views in the portfolio; sparkline shows unique visitors per day." />
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
              {agg.perDemo.slice(0, 18).map((d, i) => (
                <DemoCard key={d.key} rank={i + 1} name={labelFor(d.key)} views={d.views} uniques={d.uniques} sessions={d.sessions} trend={d.trend} />
              ))}
            </div>
          </section>
        </>
      )}

      {/* Real GitHub traffic — when published */}
      <section className="mb-10">
        <SectionHeader
          title="Live GitHub Pages traffic"
          sub="Real visit counts from the GitHub Traffic API. 14-day rolling window. Daily-refreshed by .github/workflows/traffic.yml when TRAFFIC_PAT is configured."
        />
        {ghAgg ? (
          <>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-6">
              <Kpi big={formatCompact(ghAgg.totalViews)} label="Total views · 14d" sub={`${formatNumber(ghAgg.totalViews)} clicks`} />
              <Kpi big={formatCompact(ghAgg.totalUniques)} label="Unique visitors · 14d" sub={`${formatNumber(ghAgg.totalUniques)}`} />
              <Kpi big={String(ghAgg.withTraffic)} label="Demos with traffic" sub={`of ${ghAgg.withTraffic + ghAgg.noTraffic} tracked`} />
              <Kpi big={String(ghAgg.noTraffic)} label="Demos at zero" sub="No 14-day visits" />
            </div>

            <Card title="Top referring sites · 14d · all demos" sub="Where the audience is coming from — the strongest 'who is using' signal we get without identifying anyone.">
              {ghAgg.topReferrers.length > 0 ? (
                <BarList rows={ghAgg.topReferrers.map((r) => ({ label: r.referrer, value: r.count, sub: `${r.uniques} unique` }))} valueLabel="views" />
              ) : (
                <p className="text-sm" style={{ color: 'var(--ink-muted)' }}>
                  No referrers reported by the GitHub Traffic API yet. (Referrers populate after a demo
                  accumulates enough cross-origin clicks.)
                </p>
              )}
            </Card>
          </>
        ) : (
          <div className="p-5 rounded-md font-mono text-xs"
               style={{ background: 'rgba(245,158,11,0.10)', border: '1px solid rgba(245,158,11,0.35)', color: 'var(--ink)' }}>
            <div className="mb-2 font-semibold uppercase tracking-wider text-amber-400">
              Live data not wired yet
            </div>
            <p style={{ color: 'var(--ink-muted)' }} className="mb-2 leading-relaxed">
              <code>github_traffic.json</code> hasn't been published. The page is showing the synth-preview view
              above. To turn on real traffic:
            </p>
            <ol className="list-decimal list-inside space-y-1" style={{ color: 'var(--ink-muted)' }}>
              <li>Create a GitHub PAT with <code>Administration: Read</code> on the demo repos.</li>
              <li>Add it as <code>TRAFFIC_PAT</code> repo secret on this repo.</li>
              <li>Run the <code>Fetch GitHub traffic stats</code> workflow under Actions.</li>
            </ol>
            <p className="text-[10px] mt-2" style={{ color: 'var(--ink-dim)' }}>Error: {ghError ?? 'not requested yet'}</p>
          </div>
        )}
      </section>

      {/* Per-demo GH traffic — when published */}
      {gh && (
        <section className="mb-10 grid lg:grid-cols-2 gap-6">
          {gh.demos
            .filter((d) => (d.popular_paths?.length ?? 0) > 0 || (d.top_referrers?.length ?? 0) > 0)
            .sort((a, b) => (b.views_14d?.count ?? 0) - (a.views_14d?.count ?? 0))
            .map((d) => (
              <Card key={d.repo} title={d.repo} sub={`14-day · ${formatNumber(d.views_14d?.count ?? 0)} views · ${formatNumber(d.views_14d?.uniques ?? 0)} unique`}>
                {d.popular_paths.length > 0 && (
                  <>
                    <div className="text-[10px] uppercase tracking-wider mb-1.5" style={{ color: 'var(--ink-muted)' }}>Top paths</div>
                    <BarList rows={d.popular_paths.slice(0, 6).map((p) => ({ label: p.path, value: p.count, sub: `${p.uniques}u` }))} valueLabel="" mono />
                  </>
                )}
                {d.top_referrers.length > 0 && (
                  <>
                    <div className="mt-4 text-[10px] uppercase tracking-wider mb-1.5" style={{ color: 'var(--ink-muted)' }}>Top referrers</div>
                    <BarList rows={d.top_referrers.slice(0, 6).map((r) => ({ label: r.referrer, value: r.count, sub: `${r.uniques}u` }))} valueLabel="" />
                  </>
                )}
              </Card>
            ))}
        </section>
      )}

      {/* Privacy framing */}
      <section className="mb-4 p-5 rounded-md" style={{ background: 'var(--card)', border: '1px solid var(--hairline)' }}>
        <div className="text-[10px] uppercase tracking-[0.3em] mb-3" style={{ color: 'var(--accent)' }}>
          What we can — and can't — see
        </div>
        <div className="grid sm:grid-cols-2 gap-x-8 gap-y-2 text-sm" style={{ color: 'var(--ink-muted)' }}>
          <div>
            <strong style={{ color: 'var(--ink)' }}>What we can see</strong>
            <ul className="mt-1.5 space-y-1 list-disc list-inside">
              <li>How many visits, day by day</li>
              <li>How many unique visitors (cookie-deduped by GitHub)</li>
              <li>Which demos and which pages are visited most</li>
              <li>Top referring sites (where the click came from)</li>
              <li>Approximate country (from synth geo · live geo would need analytics SDK)</li>
            </ul>
          </div>
          <div>
            <strong style={{ color: 'var(--ink)' }}>What we can't see</strong>
            <ul className="mt-1.5 space-y-1 list-disc list-inside">
              <li>Who the visitor is — no user IDs, no emails, no logins</li>
              <li>Time-of-day patterns within a session</li>
              <li>Per-visitor path traversal (which pages one person clicked through)</li>
              <li>Device, browser, or screen size — would need an SDK</li>
              <li>Anything tied to a real-world identity</li>
            </ul>
          </div>
        </div>
        <p className="mt-3 text-xs" style={{ color: 'var(--ink-dim)' }}>
          Privacy-friendly by default. To unlock the "what we can't see" column, add a self-hosted
          analytics layer (Plausible, Umami, Snowplow) — none of which need cookies or personal data.
        </p>
      </section>
    </div>
  );
}

// ============================================================
// Components
// ============================================================

function SectionHeader({ title, sub }: { title: string; sub: string }) {
  return (
    <div className="mb-3">
      <h2 className="text-lg font-semibold tracking-tight" style={{ color: 'var(--ink)' }}>{title}</h2>
      <p className="text-sm mt-0.5" style={{ color: 'var(--ink-muted)' }}>{sub}</p>
    </div>
  );
}

function Kpi({ big, label, sub }: { big: string; label: string; sub: string }) {
  return (
    <div className="border rounded-md p-4" style={{ borderColor: 'var(--hairline)', background: 'var(--card)' }}>
      <div className="text-[10px] uppercase tracking-wider" style={{ color: 'var(--ink-muted)' }}>{label}</div>
      <div className="text-2xl font-semibold mt-1" style={{ color: 'var(--ink)', fontVariantNumeric: 'tabular-nums' }}>{big}</div>
      <div className="text-[11px] mt-1 font-mono" style={{ color: 'var(--ink-dim)' }}>{sub}</div>
    </div>
  );
}

function PreviewBanner() {
  return (
    <div className="mb-6 px-3 py-2 text-[11px] rounded-md font-mono inline-flex items-center gap-2"
         style={{ background: 'rgba(34,211,238,0.10)', border: '1px solid rgba(34,211,238,0.35)', color: 'var(--ink)' }}>
      <span className="inline-block px-1.5 py-0.5 rounded font-bold uppercase tracking-wider text-[9px]"
            style={{ background: '#22d3ee', color: '#0b1220' }}>Preview</span>
      <span style={{ color: 'var(--ink-muted)' }}>
        Synth-generated 30-day view. Real numbers land here when an analytics layer is wired (see footer).
      </span>
    </div>
  );
}

function Card({ title, sub, children }: { title: string; sub?: string; children: React.ReactNode }) {
  return (
    <div className="border rounded-md" style={{ borderColor: 'var(--hairline)', background: 'var(--card)' }}>
      <div className="px-4 py-3 border-b" style={{ borderColor: 'var(--hairline)' }}>
        <div className="font-semibold" style={{ color: 'var(--ink)' }}>{title}</div>
        {sub && <div className="text-xs mt-0.5" style={{ color: 'var(--ink-dim)' }}>{sub}</div>}
      </div>
      <div className="p-4">{children}</div>
    </div>
  );
}

function BarList({ rows, valueLabel, mono = false }: { rows: { label: string; value: number; sub?: string }[]; valueLabel: string; mono?: boolean }) {
  const max = Math.max(...rows.map((r) => r.value), 1);
  return (
    <ul className="space-y-1.5">
      {rows.map((r) => (
        <li key={r.label} className="grid grid-cols-[2fr_3fr_auto] gap-2 items-center text-[12px]">
          <span className={`truncate ${mono ? 'font-mono text-[11px]' : ''}`} style={{ color: 'var(--ink)' }}>{r.label}</span>
          <span className="relative h-2 rounded-sm overflow-hidden" style={{ background: 'var(--hairline-soft, rgba(255,255,255,0.06))' }}>
            <span className="absolute inset-y-0 left-0" style={{ width: `${(r.value / max) * 100}%`, background: 'var(--accent)' }} />
          </span>
          <span className="font-mono text-[11px] tabular-nums whitespace-nowrap" style={{ color: 'var(--ink-muted)' }}>
            <strong style={{ color: 'var(--ink)' }}>{formatNumber(r.value)}</strong>{valueLabel ? ` ${valueLabel}` : ''}{r.sub ? ` · ${r.sub}` : ''}
          </span>
        </li>
      ))}
    </ul>
  );
}

function DemoCard({ rank, name, views, uniques, sessions, trend }: { rank: number; name: string; views: number; uniques: number; sessions: number; trend: number[] }) {
  return (
    <div className="border rounded-md p-3" style={{ borderColor: 'var(--hairline)', background: 'var(--card)' }}>
      <div className="flex items-baseline justify-between gap-2">
        <div className="flex items-baseline gap-2 min-w-0">
          <span className="font-mono text-[10px] tabular-nums" style={{ color: 'var(--ink-dim)' }}>#{rank}</span>
          <span className="font-semibold truncate text-[13px]" style={{ color: 'var(--ink)' }}>{name}</span>
        </div>
        <Sparkline values={trend} width={70} height={20} stroke="var(--accent)" />
      </div>
      <div className="mt-2 grid grid-cols-3 gap-2 text-[10.5px] font-mono tabular-nums" style={{ color: 'var(--ink-muted)' }}>
        <span><strong style={{ color: 'var(--ink)' }}>{formatNumber(views)}</strong> views</span>
        <span><strong style={{ color: 'var(--ink)' }}>{formatNumber(uniques)}</strong> uniq</span>
        <span><strong style={{ color: 'var(--ink)' }}>{formatNumber(sessions)}</strong> sess</span>
      </div>
    </div>
  );
}

function DailySeries({ series }: { series: { date: string; views: number; uniques: number; sessions: number }[] }) {
  if (series.length === 0) {
    return <div className="text-sm" style={{ color: 'var(--ink-muted)' }}>No data.</div>;
  }
  const maxViews = Math.max(...series.map((d) => d.views), 1);
  return (
    <div className="border rounded-md p-4" style={{ borderColor: 'var(--hairline)', background: 'var(--card)' }}>
      <div className="grid items-end gap-[2px]" style={{ gridTemplateColumns: `repeat(${series.length}, 1fr)`, height: 120 }}>
        {series.map((d) => {
          const viewsHeight = (d.views / maxViews) * 100;
          const uniquesHeight = (d.uniques / maxViews) * 100;
          return (
            <div key={d.date} className="relative h-full flex flex-col-reverse" title={`${d.date}: ${d.views} views, ${d.uniques} uniques`}>
              <div style={{ height: `${viewsHeight}%`, background: 'var(--accent)', opacity: 0.35, borderRadius: '2px 2px 0 0' }} />
              <div className="absolute inset-x-0 bottom-0" style={{ height: `${uniquesHeight}%`, background: 'var(--accent)', borderRadius: '2px 2px 0 0' }} />
            </div>
          );
        })}
      </div>
      <div className="mt-3 flex items-center justify-between text-[10.5px] font-mono" style={{ color: 'var(--ink-dim)' }}>
        <span>{series[0].date}</span>
        <span className="flex items-center gap-4">
          <span className="flex items-center gap-1.5">
            <span className="inline-block w-3 h-2 rounded-sm" style={{ background: 'var(--accent)', opacity: 0.35 }} /> page views
          </span>
          <span className="flex items-center gap-1.5">
            <span className="inline-block w-3 h-2 rounded-sm" style={{ background: 'var(--accent)' }} /> uniques
          </span>
        </span>
        <span>{series[series.length - 1].date}</span>
      </div>
    </div>
  );
}
